
name: sample
# The other report will have its own start date
start_date: "2020-03-03"
stocks:
  # Yfinance formatted stocks
  # Might just read from config.json instead
  - NEXCF
  - ACB.TO
  - BB.TO
  - N.V
  - APHA.TO
  - TTT.CN
  - HUT.TO
  - HIVE.V
  - AC.TO
  - CVE.TO
# will check against types, if array use the weights, else use equal
weights: equal
risk:
  # outputs Variance, Var, etc ...
  # Too cheap to use cloud sql and might have multiple 
  # Dynambo DB an option
  output_csv: 'risk-sample.csv'


# Date when I started buying stocks
# ref_date_1 = '2019-06-03'
# Date around when I sold everything
# ref_date_2 = '2020-03-03'