on: push

jobs:
  vm:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo This job does not specify a container.
          echo It runs directly on the virtual machine.
        name: Run on VM
  container:
    runs-on: ubuntu-latest
    container: grandfleet/fbprophet-docker:latest
    steps:
      - uses: actions/checkout@v1
      - run: |
          pip install -r requirements.txt
          python main.py
        name: Run in fbprophet container